"""Exact major-arc / homothety / tangent-circle chart.

The reusable chain is

    midpoint of the arc through the vertex
      -> antipodal second arc midpoint on the incenter axis
      -> homothety of ratio 1/2 about the vertex
      -> two right-circle power identities
      -> uniqueness of the circle through two points tangent to a fixed line.

JGEX only records that the arc midpoint lies on a perpendicular bisector and
the circumcircle.  That syntax has two branches.  The application therefore
requires a hash-bound natural-language atom identifying the arc through the
third vertex; it never selects a branch from a benchmark name.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from functools import lru_cache
import hashlib
import io
import json
import math

import matplotlib
import sympy as sp

matplotlib.use("Agg")

from matplotlib import pyplot as plt
from matplotlib.patches import Circle

from worker.backend.geometry_natural_semantics import (
    extract_geometry_natural_semantics,
)
from worker.backend.geometry_proof_hypergraph import Atom
from worker.backend.jgex_chart_parser import ChartJGEXFormulation as JGEXFormulation

Point = sp.Matrix


def _canonical(value: sp.Expr, unit_basis: sp.GroebnerBasis) -> str:
    numerator, _ = sp.together(value).as_numer_denom()
    _, remainder = unit_basis.reduce(sp.expand(numerator))
    return str(sp.factor(remainder))


def _dot(left: Point, right: Point) -> sp.Expr:
    return left.dot(right)


def _cross(left: Point, right: Point) -> sp.Expr:
    return left[0] * right[1] - left[1] * right[0]


def _distance_squared(left: Point, right: Point) -> sp.Expr:
    return _dot(left - right, left - right)


@dataclass(frozen=True)
class MajorArcHomothetyTangentCertificate:
    theorem: str
    assumptions: tuple[str, ...]
    discharged_conditions: dict[str, str]
    upstream_semantics: tuple[str, ...]
    normalization: str
    representation_chart: tuple[str, ...]
    proof_dag: tuple[str, ...]
    domain_sign_certificate: dict[str, str]
    replay_residuals: dict[str, str]
    replayed: bool
    all_conditions_discharged: bool
    certificate_sha256: str

    def to_dict(self) -> dict[str, object]:
        return asdict(self)

    def to_markdown(self) -> str:
        residuals = "\n".join(
            f"- `{name}`: `{value}`" for name, value in self.replay_residuals.items()
        )
        signs = "\n".join(
            f"- `{name}`: {value}"
            for name, value in self.domain_sign_certificate.items()
        )
        return "\n".join(
            (
                "# Major-arc homothety / tangent-circle chart",
                "",
                "## Theorem",
                "",
                (
                    "For the typed construction in the chart, the incenter axis "
                    "is tangent to the circumcircle of the reflected "
                    "parallelogram/projection triangle."
                ),
                "",
                "## Reusable proof",
                "",
                "1. The ratio-1/2 homothety about A sends P,Q,R to M,N,U.",
                "2. If S is the midpoint of AI, then U is the foot from A to SN.",
                "3. The right-triangle similarity gives SU*SN=SA^2=SI^2.",
                "4. For the antipodal arc midpoint D, DM*DN=DB^2=DI^2.",
                "5. Hence the circles IUN and IMN are both tangent to AI at I.",
                "6. Uniqueness gives I,M,N,U concyclic; homothety returns the goal.",
                "",
                "## Domain and branch certificate",
                "",
                signs,
                "",
                "## Exact replay",
                "",
                residuals,
                "",
                f"- all identities replayed: `{self.replayed}`",
                f"- all conditions discharged: `{self.all_conditions_discharged}`",
                f"- certificate SHA-256: `{self.certificate_sha256}`",
                "",
            )
        )


@dataclass(frozen=True)
class JGEXMajorArcHomothetyTangentApplication:
    theorem: str
    source_sha256: str
    natural_statement_sha256: str
    natural_statement: str
    natural_semantic_atoms: tuple[str, ...]
    roles: dict[str, str]
    matched_constructions: tuple[str, ...]
    goal: str
    proof_bridge: str
    chart_certificate_sha256: str
    nondegeneracy_obligations: tuple[str, ...]
    undischarged_nondegeneracy_obligations: tuple[str, ...]
    replayed: bool

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


@lru_cache(maxsize=1)
def certify_major_arc_homothety_tangent_chart() -> (
    MajorArcHomothetyTangentCertificate
):
    # alpha and beta are half central angles.  The replay runs in the exact
    # quotient ring generated by the two unit-circle identities.
    sin_alpha, cos_alpha, sin_beta, cos_beta = sp.symbols(
        "sin_alpha cos_alpha sin_beta cos_beta",
        real=True,
    )
    unit_basis = sp.groebner(
        (
            sin_alpha**2 + cos_alpha**2 - 1,
            sin_beta**2 + cos_beta**2 - 1,
        ),
        cos_alpha,
        cos_beta,
        sin_alpha,
        sin_beta,
        order="lex",
    )

    o = sp.Matrix((0, 0))
    a = sp.Matrix(
        (
            1 - 2 * sin_alpha**2,
            2 * sin_alpha * cos_alpha,
        )
    )
    b = sp.Matrix(
        (
            1 - 2 * sin_beta**2,
            2 * sin_beta * cos_beta,
        )
    )
    c = sp.Matrix(
        (
            1 - 2 * sin_beta**2,
            -2 * sin_beta * cos_beta,
        )
    )
    d = sp.Matrix((1, 0))
    n = sp.Matrix((-1, 0))
    m = (b + c) / 2
    i = sp.Matrix(
        (
            1 - 2 * sin_alpha * sin_beta,
            2 * cos_alpha * sin_beta,
        )
    )
    s = (a + i) / 2

    sn_squared = _distance_squared(s, n)
    sa_squared = _distance_squared(s, a)
    u = s + sa_squared / sn_squared * (n - s)

    p_point = b + c - a
    q_point = 2 * n - a
    r = 2 * u - a

    small_center = sp.Matrix(
        (
            -sin_beta**2,
            (
                2 * sin_beta
                - sin_alpha
                - sin_alpha * sin_beta**2
            )
            / cos_alpha,
        )
    )
    o1 = 2 * small_center - a
    tangent_foot = 2 * i - a

    ab_cross = _cross(i - a, b - a)
    ac_cross = _cross(i - a, c - a)
    bc_cross = _cross(i - b, c - b)
    raw_residuals: dict[str, sp.Expr] = {
        "A_on_unit_circumcircle": _distance_squared(a, o) - 1,
        "B_on_unit_circumcircle": _distance_squared(b, o) - 1,
        "C_on_unit_circumcircle": _distance_squared(c, o) - 1,
        "N_on_unit_circumcircle": _distance_squared(n, o) - 1,
        "N_on_perpendicular_bisector_BC": (
            _distance_squared(n, b) - _distance_squared(n, c)
        ),
        "D_antipodal_to_N_x": d[0] + n[0],
        "D_antipodal_to_N_y": d[1] + n[1],
        "I_on_AD": _cross(i - a, d - a),
        "I_equidistant_from_AB_BC_squared": (
            ab_cross**2 * _distance_squared(c, b)
            - bc_cross**2 * _distance_squared(b, a)
        ),
        "I_equidistant_from_AC_BC_squared": (
            ac_cross**2 * _distance_squared(c, b)
            - bc_cross**2 * _distance_squared(c, a)
        ),
        "M_midpoint_BC_x": m[0] - (b[0] + c[0]) / 2,
        "M_midpoint_BC_y": m[1] - (b[1] + c[1]) / 2,
        "P_parallelogram_x": p_point[0] - (b[0] + c[0] - a[0]),
        "P_parallelogram_y": p_point[1] - (b[1] + c[1] - a[1]),
        "Q_reflection_in_N_x": q_point[0] - (2 * n[0] - a[0]),
        "Q_reflection_in_N_y": q_point[1] - (2 * n[1] - a[1]),
        "S_midpoint_AI_x": s[0] - (a[0] + i[0]) / 2,
        "S_midpoint_AI_y": s[1] - (a[1] + i[1]) / 2,
        "AN_perpendicular_AS": _dot(n - a, s - a),
        "U_on_SN": _cross(u - s, n - s),
        "AU_perpendicular_SN": _dot(u - a, n - s),
        "SU_times_SN_equals_SA_squared": (
            _dot(u - s, n - s) - sa_squared
        ),
        "SI_squared_equals_SA_squared": (
            _distance_squared(s, i) - sa_squared
        ),
        "R_on_QI": _cross(r - q_point, i - q_point),
        "AR_perpendicular_QI": _dot(r - a, i - q_point),
        "P_maps_to_M_x": (a[0] + p_point[0]) / 2 - m[0],
        "P_maps_to_M_y": (a[1] + p_point[1]) / 2 - m[1],
        "Q_maps_to_N_x": (a[0] + q_point[0]) / 2 - n[0],
        "Q_maps_to_N_y": (a[1] + q_point[1]) / 2 - n[1],
        "R_maps_to_U_x": (a[0] + r[0]) / 2 - u[0],
        "R_maps_to_U_y": (a[1] + r[1]) / 2 - u[1],
        "DM_times_DN_equals_DB_squared": (
            (d[0] - m[0]) * (d[0] - n[0]) - _distance_squared(d, b)
        ),
        "DI_squared_equals_DB_squared": (
            _distance_squared(d, i) - _distance_squared(d, b)
        ),
        "small_circle_M_equals_I": (
            _distance_squared(small_center, m)
            - _distance_squared(small_center, i)
        ),
        "small_circle_N_equals_I": (
            _distance_squared(small_center, n)
            - _distance_squared(small_center, i)
        ),
        "small_circle_U_equals_I": (
            _distance_squared(small_center, u)
            - _distance_squared(small_center, i)
        ),
        "small_radius_at_I_perpendicular_AI": (
            _dot(small_center - i, i - a)
        ),
        "O1_equidistant_P_Q": (
            _distance_squared(o1, p_point)
            - _distance_squared(o1, q_point)
        ),
        "O1_equidistant_P_R": (
            _distance_squared(o1, p_point) - _distance_squared(o1, r)
        ),
        "tangent_foot_on_AI": _cross(tangent_foot - a, i - a),
        "O1_foot_perpendicular_AI": _dot(tangent_foot - o1, i - a),
        "goal_O1P_equals_O1T_squared": (
            _distance_squared(o1, p_point)
            - _distance_squared(o1, tangent_foot)
        ),
    }
    residuals = {
        name: _canonical(value, unit_basis)
        for name, value in raw_residuals.items()
    }
    replayed = all(value == "0" for value in residuals.values())

    assumptions = (
        "ABC is acute",
        "N is the midpoint of the circumcircle arc from B to C through A",
        "I and O are the incenter and circumcenter of ABC",
        "M is the midpoint of BC and ABPC is a parallelogram",
        "Q is the reflection of A in N and R is the foot from A to QI",
        "O1 is the circumcenter of PQR and T is the foot from O1 to AI",
    )
    domain_sign_certificate = {
        "acute_branch": (
            "Choose 0<beta<pi/4<alpha<pi/2 and alpha+beta>pi/2; "
            "then A=(cos 2alpha,sin 2alpha), B=(cos 2beta,sin 2beta), "
            "C=(cos 2beta,-sin 2beta) form an acute nondegenerate triangle."
        ),
        "rational_parameter_domain": (
            "p=tan(alpha/2), q=tan(beta/2) satisfy "
            "0<q<sqrt(2)-1<p<1 and p+q>1-pq."
        ),
        "arc_branch": (
            "N=(-1,0) lies on the B-to-C arc containing A; D=(1,0) is its "
            "antipodal midpoint on AI.  The typed natural atom selects N."
        ),
        "denominators": (
            "1+p^2, 1+q^2 and cos(alpha) are positive.  |SN|^2>0 because "
            "S lies inside ABC while N lies on its circumcircle."
        ),
        "incenter_branch": (
            "The equal-distance residuals plus 0<q<p<1 place I inside ABC, "
            "selecting the internal rather than an excentral branch."
        ),
        "tangency_uniqueness": (
            "A circle tangent to AI at I has center on the perpendicular at I; "
            "requiring it to pass through N fixes that center uniquely."
        ),
    }
    discharged_conditions = {
        assumptions[0]: "The hash-bound natural semantics supplies acute(A,B,C).",
        assumptions[1]: (
            "The hash-bound atom arc_midpoint_through(N,B,A,C) fixes the lost branch."
        ),
        assumptions[2]: "The JGEX constructors are matched and their defining residuals replay.",
        assumptions[3]: "The midpoint and reflection/parallelogram identities replay exactly.",
        assumptions[4]: "The homothety and two perpendicular incidences replay exactly.",
        assumptions[5]: "Both radius equalities and the tangent-foot goal replay exactly.",
    }
    payload = {
        "theorem": "major-arc-homothety-right-circle-tangent",
        "assumptions": assumptions,
        "discharged_conditions": discharged_conditions,
        "upstream_semantics": (
            "Natural-language acute and arc-through qualifiers are typed and hash-bound.",
            "JGEX on_bline/on_circle alone is intentionally insufficient to select N.",
            "JGEX mirror, foot, midpoint, incenter and circumcenter retain standard semantics.",
            "No problem identifier or expected conclusion is used by the matcher.",
        ),
        "normalization": (
            "Apply an orientation-preserving similarity to the unit circumcircle, "
            "put the minor B-C arc midpoint at D=(1,0), and its antipode at N=(-1,0). "
            "Normalize residuals modulo sin(alpha)^2+cos(alpha)^2=1 and "
            "sin(beta)^2+cos(beta)^2=1."
        ),
        "representation_chart": (
            "arc-through midpoint -> antipodal midpoint on the incenter axis",
            "parallelogram/reflections/projection -> ratio-1/2 homothety",
            "right-triangle similarity -> tangent-length power identity",
            "arc midpoint angles -> second tangent-length power identity",
            "two tangent circles through I,N -> uniqueness -> concyclicity",
            "inverse homothety -> tangent circumcircle of PQR",
        ),
        "proof_dag": (
            "Introduce S, the midpoint of AI, and D, the antipode of N.",
            "The homothety H(A,1/2) maps P,Q,R to M,N,U respectively.",
            (
                "Because AN is perpendicular to AS and U is the foot on SN, "
                "triangles ASN and USA are similar."
            ),
            "Therefore SU*SN=SA^2=SI^2, so AI is tangent at I to circle IUN.",
            "Arc-midpoint angles give DM*DN=DB^2=DI^2, so AI is tangent at I to circle IMN.",
            "The circle through I,N tangent to AI at I is unique; hence I,M,N,U are concyclic.",
            "Applying H(A,2) proves AI tangent to the circumcircle of PQR.",
            (
                "The exact coordinate replay independently verifies O1P=O1T "
                "and every construction incidence."
            ),
        ),
        "domain_sign_certificate": domain_sign_certificate,
        "replay_residuals": residuals,
        "replayed": replayed,
        "all_conditions_discharged": replayed,
    }
    digest = hashlib.sha256(
        json.dumps(payload, ensure_ascii=True, sort_keys=True).encode("utf-8")
    ).hexdigest()
    return MajorArcHomothetyTangentCertificate(
        **payload,
        certificate_sha256=digest,
    )


def _records(formulation: JGEXFormulation) -> tuple[dict[str, object], ...]:
    return tuple(
        {
            "outputs": tuple(map(str, clause.points)),
            "constructions": tuple(
                (construction.name, tuple(map(str, construction.args)))
                for construction in clause.constructions
            ),
        }
        for clause in formulation.setup_clauses
    )


def _canonical_construction(
    construction: tuple[str, tuple[str, ...]],
) -> tuple[str, tuple[str, ...]]:
    name, args = construction
    if name in {"circumcenter", "incenter"} and len(args) == 3:
        return name, tuple(sorted(args))
    if name in {"midpoint", "on_bline"} and len(args) == 2:
        return name, tuple(sorted(args))
    if name == "foot" and len(args) == 3:
        return name, (args[0], *sorted(args[1:]))
    return construction


def _single(
    records: tuple[dict[str, object], ...],
    construction: tuple[str, tuple[str, ...]],
) -> str | None:
    expected = _canonical_construction(construction)
    matches = {
        str(record["outputs"][0])
        for record in records
        if len(record["outputs"]) == 1
        and len(record["constructions"]) == 1
        and _canonical_construction(record["constructions"][0]) == expected
    }
    return next(iter(matches)) if len(matches) == 1 else None


def _joint(
    records: tuple[dict[str, object], ...],
    constructions: tuple[tuple[str, tuple[str, ...]], ...],
) -> str | None:
    expected = sorted(map(_canonical_construction, constructions), key=repr)
    matches = {
        str(record["outputs"][0])
        for record in records
        if len(record["outputs"]) == 1
        and sorted(map(_canonical_construction, record["constructions"]), key=repr)
        == expected
    }
    return next(iter(matches)) if len(matches) == 1 else None


def certify_jgex_major_arc_homothety_tangent_application(
    source: str,
    natural_statement: str | None = None,
) -> JGEXMajorArcHomothetyTangentApplication:
    normalized = source.strip()
    natural = (natural_statement or "").strip()
    semantics = extract_geometry_natural_semantics(natural)
    formulation = JGEXFormulation.from_text(normalized)
    records = _records(formulation)
    candidates: dict[tuple[tuple[str, str], ...], dict[str, str]] = {}

    triangles = [
        tuple(map(str, record["outputs"]))
        for record in records
        if len(record["outputs"]) == 3
        and record["constructions"] == (("triangle", ()),)
    ]
    for triangle in triangles:
        a, b, c = triangle
        i = _single(records, ("incenter", (a, b, c)))
        o = _single(records, ("circumcenter", (a, b, c)))
        if not i or not o:
            continue
        n = _joint(
            records,
            (("on_bline", (b, c)), ("on_circle", (o, a))),
        )
        m = _single(records, ("midpoint", (b, c)))
        if not n or not m:
            continue
        p_point = _single(records, ("mirror", (a, m)))
        q_point = _single(records, ("mirror", (a, n)))
        if not p_point or not q_point:
            continue
        r = _single(records, ("foot", (a, q_point, i)))
        if not r:
            continue
        o1 = _single(records, ("circumcenter", (p_point, q_point, r)))
        if not o1:
            continue
        tangent_foot = _single(records, ("foot", (o1, a, i)))
        if not tangent_foot:
            continue
        roles = {
            "A": a,
            "B": b,
            "C": c,
            "I": i,
            "O": o,
            "N": n,
            "M": m,
            "P": p_point,
            "Q": q_point,
            "R": r,
            "O1": o1,
            "T": tangent_foot,
        }
        candidates[tuple(sorted(roles.items()))] = roles

    goal = str(formulation.goals[0]) if len(formulation.goals) == 1 else ""
    accepted: list[dict[str, str]] = []
    if len(formulation.goals) == 1:
        actual_goal = Atom(
            formulation.goals[0].predicate,
            formulation.goals[0].args,
        ).canonical()
        for roles in candidates.values():
            expected_goal = Atom(
                "cong",
                (roles["O1"], roles["P"], roles["O1"], roles["T"]),
            ).canonical()
            semantic_match = (
                semantics.has_acute_triangle(
                    (roles["A"], roles["B"], roles["C"])
                )
                and semantics.has_arc_midpoint_through(
                    roles["N"],
                    (roles["B"], roles["C"]),
                    roles["A"],
                )
            )
            if actual_goal == expected_goal and semantic_match:
                accepted.append(roles)

    chart = certify_major_arc_homothety_tangent_chart()
    replayed = len(accepted) == 1 and chart.replayed
    roles = accepted[0] if len(accepted) == 1 else {}
    obligations = (
        "ABC is acute",
        "N is the midpoint of the B-to-C circumcircle arc through A",
        "all reflected and projected points are finite and nondegenerate",
    )
    return JGEXMajorArcHomothetyTangentApplication(
        theorem=chart.theorem,
        source_sha256=hashlib.sha256(normalized.encode("utf-8")).hexdigest(),
        natural_statement_sha256=semantics.statement_sha256,
        natural_statement=natural,
        natural_semantic_atoms=semantics.typed_atoms,
        roles=roles,
        matched_constructions=(
            "triangle",
            "incenter",
            "circumcenter(ABC)",
            "on_bline+on_circle",
            "midpoint",
            "mirror(A,M)",
            "mirror(A,N)",
            "foot(A,QI)",
            "circumcenter(PQR)",
            "foot(O1,AI)",
        )
        if roles
        else (),
        goal=goal,
        proof_bridge=(
            "arc-through branch -> antipode -> H(A,1/2) -> two power "
            "identities -> unique tangent circle -> inverse homothety"
        ),
        chart_certificate_sha256=chart.certificate_sha256,
        nondegeneracy_obligations=obligations,
        undischarged_nondegeneracy_obligations=() if replayed else obligations,
        replayed=replayed,
    )


def render_major_arc_homothety_tangent_chart_svg() -> str:
    alpha = math.radians(62)
    beta = math.radians(32)
    sa, ca = math.sin(alpha), math.cos(alpha)
    sb, cb = math.sin(beta), math.cos(beta)
    a = (1 - 2 * sa * sa, 2 * sa * ca)
    b = (1 - 2 * sb * sb, 2 * sb * cb)
    c = (1 - 2 * sb * sb, -2 * sb * cb)
    n = (-1.0, 0.0)
    d = (1.0, 0.0)
    m = ((b[0] + c[0]) / 2, 0.0)
    i = (1 - 2 * sa * sb, 2 * ca * sb)
    s = ((a[0] + i[0]) / 2, (a[1] + i[1]) / 2)
    sn2 = (n[0] - s[0]) ** 2 + (n[1] - s[1]) ** 2
    sa2 = (a[0] - s[0]) ** 2 + (a[1] - s[1]) ** 2
    u = (
        s[0] + sa2 / sn2 * (n[0] - s[0]),
        s[1] + sa2 / sn2 * (n[1] - s[1]),
    )
    p_point = (b[0] + c[0] - a[0], b[1] + c[1] - a[1])
    q_point = (2 * n[0] - a[0], 2 * n[1] - a[1])
    r = (2 * u[0] - a[0], 2 * u[1] - a[1])
    small_center = (
        -sb * sb,
        (2 * sb - sa - sa * sb * sb) / ca,
    )
    o1 = (2 * small_center[0] - a[0], 2 * small_center[1] - a[1])
    small_radius = math.dist(small_center, i)
    large_radius = math.dist(o1, p_point)

    fig, ax = plt.subplots(figsize=(9.2, 6.0))
    fig.patch.set_facecolor("#07090c")
    ax.set_facecolor("#07090c")
    ax.add_patch(Circle((0, 0), 1, fill=False, color="#34424f", linewidth=1.2))
    ax.add_patch(
        Circle(
            small_center,
            small_radius,
            fill=False,
            color="#ffb454",
            linewidth=1.4,
            linestyle="--",
        )
    )
    ax.add_patch(
        Circle(o1, large_radius, fill=False, color="#31d7e8", linewidth=2.0)
    )
    ax.plot(
        [a[0], i[0], 2 * i[0] - a[0]],
        [a[1], i[1], 2 * i[1] - a[1]],
        color="#ecf3f8",
        linewidth=1.4,
    )
    ax.plot(
        [p_point[0], q_point[0], r[0], p_point[0]],
        [p_point[1], q_point[1], r[1], p_point[1]],
        color="#31d7e8",
        linewidth=1.1,
    )
    ax.plot(
        [m[0], n[0], u[0], m[0]],
        [m[1], n[1], u[1], m[1]],
        color="#ffb454",
        linewidth=1.0,
        linestyle="--",
    )
    ax.plot([a[0], n[0]], [a[1], n[1]], color="#667683", linewidth=0.9)
    ax.plot([s[0], n[0]], [s[1], n[1]], color="#667683", linewidth=0.9)

    points = {
        "A": a,
        "B": b,
        "C": c,
        "D": d,
        "I": i,
        "N": n,
        "M": m,
        "U": u,
        "P": p_point,
        "Q": q_point,
        "R": r,
        "O1": o1,
    }
    for label, point in points.items():
        color = "#31d7e8" if label in {"P", "Q", "R", "O1"} else "#f3f6f8"
        ax.scatter([point[0]], [point[1]], s=22, color=color, zorder=4)
        ax.text(
            point[0] + 0.035,
            point[1] + 0.035,
            label,
            color=color,
            fontsize=9,
        )
    ax.set_aspect("equal", adjustable="datalim")
    ax.axis("off")
    ax.set_title(
        "H(A, 1/2):  PQR -> MNU  |  tangent axis AI",
        color="#e7edf2",
        fontsize=12,
        pad=12,
    )
    fig.tight_layout()
    buffer = io.StringIO()
    fig.savefig(buffer, format="svg", transparent=False, bbox_inches="tight")
    plt.close(fig)
    return buffer.getvalue()


__all__ = [
    "JGEXMajorArcHomothetyTangentApplication",
    "MajorArcHomothetyTangentCertificate",
    "certify_jgex_major_arc_homothety_tangent_application",
    "certify_major_arc_homothety_tangent_chart",
    "render_major_arc_homothety_tangent_chart_svg",
]
