"""Tests for geometric instruction parsing, representation policy learning, and wave-optics roundtrip."""
from fractions import Fraction
import json
from pathlib import Path
import sys
import numpy as np
import pytest

repo_root = Path(__file__).resolve().parent.parent
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from math_os_prototype import geometry_alphabet as alpha
from math_os_prototype import geometry_instruction_parser as parser
from math_os_prototype import geometry_letter_construction as constr
from math_os_prototype import geometry_raster as raster
from math_os_prototype import geometry_reading as reading
from math_os_prototype import geometry_recognition_policy as rec_policy
from math_os_prototype import geometry_self_improvement as loop
from math_os_prototype.wave_optics_system import (
    FresnelPropagation,
    GridSpec2D,
    OpticalTrain,
    WaveField2D,
    phase_retrieval_gerchberg_saxton,
)


def test_instruction_parser_valid_and_invalid():
    """Verify that valid commands generate distinct tasks and invalid commands are rejected."""
    external_pts = {"a": [0, 0], "b": [4, 0], "c": [2, 3]}

    # Valid command 1: PERP
    res_perp = parser.parse_geometric_instruction("PERP", external_pts)
    assert res_perp["valid"] is True
    assert res_perp["command"] == "PERP"
    assert res_perp["task"]["points"] == {"a": [0, 0], "b": [4, 0], "c": [2, 3]}
    assert any(g["predicate"] == "perp" for g in res_perp["task"]["goals"])

    # Valid command 2: MIDP
    res_midp = parser.parse_geometric_instruction("MIDP", external_pts)
    assert res_midp["valid"] is True
    assert res_midp["command"] == "MIDP"
    assert res_midp["task"]["points"] == {"a": [0, 0], "b": [4, 0]}
    assert any(g["predicate"] == "cong" for g in res_midp["task"]["goals"])
    # Distinct tasks
    assert res_perp["task"] != res_midp["task"]

    # Missing external points
    res_missing = parser.parse_geometric_instruction("PERP", {"a": [0, 0], "b": [4, 0]})
    assert res_missing["valid"] is False
    assert "Missing required external points" in res_missing["reason"]
    assert res_missing["task"] is None

    # Invalid command: FOOBAR
    res_invalid = parser.parse_geometric_instruction("FOOBAR", external_pts)
    assert res_invalid["valid"] is False
    assert "Unknown or unsupported" in res_invalid["reason"]
    assert res_invalid["task"] is None


def test_solver_integration_with_parser():
    """Verify that loop.solve successfully solves the task generated by the parser."""
    external_pts = {"a": [0, 0], "b": [4, 0], "c": [2, 3]}
    res_parsed = parser.parse_geometric_instruction("PERP", external_pts)
    assert res_parsed["valid"] is True

    solve_res = loop.solve(res_parsed["task"], applications=10)
    assert solve_res["solved"] is True
    assert solve_res["solution"]["term"]["op"] == "foot"


def test_recognition_policy_train_save_load(tmp_path):
    """Verify representation policy serialization, loading, and training."""
    policy_file = tmp_path / "test_policy.json"

    # Default policy save and load
    rec_policy.save_recognition_policy(rec_policy.DEFAULT_POLICY, policy_file)
    assert policy_file.exists()

    loaded = rec_policy.load_recognition_policy(policy_file)
    assert loaded == rec_policy.DEFAULT_POLICY

    # Evaluate candidates on small subset
    subset_ref = {"P": alpha.ROMAN["P"], "E": alpha.ROMAN["E"]}
    subset_val = {"P": alpha.NARROW["P"], "E": alpha.NARROW["E"]}

    best_policy, report = rec_policy.train_recognition_policy(
        reference_alphabet=subset_ref,
        validation_letters=subset_val,
        current_policy=rec_policy.DEFAULT_POLICY,
    )
    assert isinstance(best_policy, rec_policy.RecognitionPolicy)
    assert "candidates_evaluated" in report
    assert len(report["candidates_evaluated"]) == len(rec_policy.CANDIDATE_POLICIES)


def test_wave_optics_geometric_roundtrip():
    """Verify: scene bitmap -> target intensity -> phase retrieval -> wave propagation -> binarization -> recognition."""
    # 1. Geometric scene: construct letter 'P'
    names, program, coords = constr.build_lattice(6, 6)
    replayed = constr.replay(program)
    named_alphabet = constr.as_names(alpha.ROMAN, names)
    built_letters = constr.as_coordinates(named_alphabet, replayed)
    built_p = built_letters["P"]

    scale = 8
    radius = Fraction(3, 8) * scale
    segs = [
        (
            (Fraction(a[0]) * scale, Fraction(a[1]) * scale),
            (Fraction(b[0]) * scale, Fraction(b[1]) * scale),
        )
        for a, b in raster.polyline_segments(built_p)
    ]
    w = 64
    h = 64
    moved = [
        (
            (a[0] + 12 * scale // 4, a[1] + 8 * scale // 4),
            (b[0] + 12 * scale // 4, b[1] + 8 * scale // 4),
        )
        for a, b in segs
    ]
    scene_bitmap = raster.render(moved, radius, w, h)
    assert scene_bitmap.count() > 0

    # 2. Convert scene_bitmap directly into wave optics target intensity (no redrawing!)
    target_intensity = np.zeros((h, w), dtype=np.float64)
    for x, y in scene_bitmap.black:
        target_intensity[y, x] = 1.0

    # Physical parameters
    wavelength = 532e-9  # 532 nm
    dx = 10e-6  # 10 um pitch
    grid = GridSpec2D(nx=w, ny=h, dx=dx, dy=dx)
    z = 0.008  # 8 mm propagation distance (z < z_crit)

    # 3. Phase retrieval via Gerchberg-Saxton
    optical_train = OpticalTrain()
    optical_train.add(FresnelPropagation(distance=z, wavelength=wavelength))
    input_amplitude = np.ones((h, w), dtype=np.float64)

    phase_slm, errors = phase_retrieval_gerchberg_saxton(
        target_intensity=target_intensity,
        optical_train=optical_train,
        input_amplitude=input_amplitude,
        grid=grid,
        wavelength=wavelength,
        iterations=15,
    )
    assert len(errors) == 15
    assert errors[-1] < errors[0]

    # 4. Forward wave propagation to sensor plane
    field_in = WaveField2D(
        u=input_amplitude * np.exp(1j * phase_slm),
        grid=grid,
        wavelength=wavelength,
        z=0.0,
    )
    field_sensor = optical_train.apply(field_in)
    i_sensor = field_sensor.intensity()

    # 5. Objective binarization condition (Otsu thresholding, no arbitrary tuning)
    # Normalize sensor intensity to [0, 255] integer bins for Otsu calculation
    norm_i = (i_sensor - np.min(i_sensor)) / (np.max(i_sensor) - np.min(i_sensor) + 1e-12)
    hist, bin_edges = np.histogram(norm_i, bins=64, range=(0.0, 1.0))
    prob = hist / float(np.sum(hist))
    omega = np.cumsum(prob)
    mu = np.cumsum(prob * np.arange(len(prob)))
    mu_t = mu[-1]

    # Maximize between-class variance
    sigma_b_squared = np.zeros(len(prob))
    for t in range(len(prob)):
        if 0 < omega[t] < 1.0:
            sigma_b_squared[t] = ((mu_t * omega[t] - mu[t]) ** 2) / (omega[t] * (1.0 - omega[t]))
    best_bin = np.argmax(sigma_b_squared)
    threshold_val = bin_edges[best_bin]

    # Convert back to Bitmap using objective condition
    reconstructed_black = {
        (x, y)
        for y in range(h)
        for x in range(w)
        if norm_i[y, x] >= threshold_val
    }
    reconstructed_bitmap = raster.Bitmap(w, h, reconstructed_black)
    assert reconstructed_bitmap.count() > 0

    # 6. Re-read using geometric reader
    lib = reading.library_from(built_letters)
    read_res = reading.read(reconstructed_bitmap, lib)
    assert read_res["letter"] == "P"


def test_checkpoint_and_acquired_library_persistence(tmp_path):
    """Verify AcquiredLibrary serialization and checkpoint restore semantics."""
    from math_os_prototype import geometry_acquired_library as acqlib
    import subprocess

    # 1. AcquiredLibrary to_dict and from_dict roundtrip
    lib = acqlib.AcquiredLibrary()
    prog = {
        "params": ["p0", "p1"],
        "steps": [{"out": "s0", "prim": "midpoint", "args": ["p0", "p1"]}],
        "result": "s0",
    }
    lib.register(prog, {("midp", ("v", "p0", "p1")): {"test": True}}, source={"task": "t1"})
    state_dict = lib.to_dict()

    lib_restored = acqlib.AcquiredLibrary.from_dict(state_dict)
    assert len(lib_restored.acquired) == 1
    assert lib_restored.holds(prog)

    # 2. Checkpoint restoration script in initial mode
    res_init = subprocess.run(
        [sys.executable, str(repo_root / "scripts" / "restore_or_init_checkpoint.py"), "--mode", "initial"],
        capture_output=True,
        text=True,
    )
    assert res_init.returncode == 0
    assert (repo_root / "reports" / "checkpoint_manifest.json").exists()

    # 3. Checkpoint restoration script in continuous mode with existing dir
    res_cont = subprocess.run(
        [
            sys.executable,
            str(repo_root / "scripts" / "restore_or_init_checkpoint.py"),
            "--mode",
            "continuous",
            "--checkpoint",
            "reports",
        ],
        capture_output=True,
        text=True,
    )
    assert res_cont.returncode == 0

    # 4. Checkpoint restoration script in continuous mode with missing checkpoint must fail (code 1)
    res_fail = subprocess.run(
        [
            sys.executable,
            str(repo_root / "scripts" / "restore_or_init_checkpoint.py"),
            "--mode",
            "continuous",
            "--checkpoint",
            str(tmp_path / "non_existent"),
        ],
        capture_output=True,
        text=True,
    )
    assert res_fail.returncode == 1
    assert "Cannot silently fall back to initial state" in res_fail.stderr
