import assert from 'node:assert/strict'
import test from 'node:test'

import {
  PROBLEM_TASK_PRIMITIVES,
  compressProblemTaskAlgebra,
  expandProblemTaskCoreAlgebra,
  problemTaskCorePrimitiveSet,
  type ProblemTaskAlgebra,
} from './problem-task-algebra'

test('all twelve task operations are generated by five reversible core laws', () => {
  const program: ProblemTaskAlgebra = {
    schema: 1,
    input: 'typed-object',
    operations: PROBLEM_TASK_PRIMITIVES.map(operator => ({ operator, output: 'typed-object' })),
    output: 'typed-object',
    complete: true,
  }
  const core = compressProblemTaskAlgebra(program)

  assert.deepEqual(expandProblemTaskCoreAlgebra(core), program)
  assert.deepEqual(problemTaskCorePrimitiveSet([core]), [
    'transform',
    'combine',
    'restrict',
    'aggregate',
    'canonicalize',
  ])
})

test('semantic task laws remain distinct inside a shared core family', () => {
  const make = (operator: 'period' | 'eliminate'): ProblemTaskAlgebra => ({
    schema: 1,
    input: 'finite-orbit',
    operations: [{ operator, output: operator === 'period' ? 'period-data' : 'polynomial' }],
    output: operator === 'period' ? 'period-data' : 'polynomial',
    complete: true,
  })
  const period = compressProblemTaskAlgebra(make('period'))
  const eliminate = compressProblemTaskAlgebra(make('eliminate'))

  assert.equal(period.operations[0].operator, 'aggregate')
  assert.equal(eliminate.operations[0].operator, 'aggregate')
  assert.notDeepEqual(period, eliminate)
})

test('rejects a core operation paired with the wrong typed law', () => {
  assert.throws(() => expandProblemTaskCoreAlgebra({
    schema: 1,
    input: 'sequence',
    operations: [{ operator: 'combine', law: 'preimage', output: 'index-set' }],
    output: 'index-set',
    complete: true,
  }), /does not belong/)
})
