import Image from 'next/image'
import Link from 'next/link'
import {
  ArrowLeft,
  ArrowRight,
  Box,
  Download,
  FileJson2,
  Github,
  Layers3,
  Ruler,
} from 'lucide-react'
import type { Lang } from '@/lib/mortra/i18n'
import { LabNotchNav } from './LabNotchNav'
import { ShaderField } from './ShaderField'
import styles from '@/app/research/engineering-geometry/engineeringGeometry.module.css'

const operations = [
  ['transform', '位置・向き・対称性を変える'],
  ['sweep', '断面を経路に沿って運ぶ'],
  ['combine', '形状の和・差・共通部分を取る'],
  ['select', '面・辺・境界を選ぶ'],
  ['slice', '切断面との交わりを取る'],
  ['project', '正投影・等角投影へ写す'],
  ['constrain', '寸法と成立条件を検査する'],
  ['annotate', '寸法・中心線・注記を結び付ける'],
] as const

const drawings = [
  {
    src: '/research/engineering-geometry/spoked-wheel.svg',
    id: 'SPK-001',
    en: 'Spoked wheel',
    ja: 'スポーク車輪',
    detailEn: 'Repeated transforms, swept profiles and Boolean union.',
    detailJa: '反復変換、断面の移動、形状の和で構成。',
  },
  {
    src: '/research/engineering-geometry/clevis-bracket.svg',
    id: 'CLV-001',
    en: 'Clevis bracket',
    ja: 'クレビス',
    detailEn: 'Paired lugs, cross bore and an exact section from one B-rep.',
    detailJa: '二枚のラグと横穴を持つB-repから断面を導出。',
  },
  {
    src: '/research/engineering-geometry/cross-drilled-manifold.svg',
    id: 'MNF-001',
    en: 'Cross-drilled manifold',
    ja: '三軸交差流路ブロック',
    detailEn: 'Three orthogonal passages, hidden lines and clipped hatching.',
    detailJa: '三方向の流路、隠れ線、断面ハッチを同じ形状から生成。',
  },
] as const

const pipeline = [
  ['01', 'Typed program', 'Cell(k, R^n) と8射で構成を記録'],
  ['02', 'Exact B-rep', 'OpenCascadeで立体と位相を実行'],
  ['03', 'Derived views', '投影、隠れ線、断面をB-repから導出'],
  ['04', 'Drawing', '中心線、寸法、注記を意味対象へ接続'],
  ['05', 'Artifacts', 'STEP、STL、SVG、DXF、JSONを保存'],
] as const

const resultRows = [
  ['基底形状族', '5 / 5', 'フランジ、段付き軸、ブラケット、遷移ダクト、格子'],
  ['寸法未見', '3 / 3', '寸法・穴数を変えた未見パラメータ'],
  ['形状族未見', '3 / 3', 'スポーク車輪、クレビス、三軸交差流路'],
  ['厳密形状', '11 / 11', '妥当な単一ソリッドとして再生'],
  ['投影図', '44 / 44', 'TOP、FRONT、RIGHT、ISOMETRICが図面内に収容'],
  ['追加した演算族', '0', '未見6件のための部品別命令は追加していない'],
] as const

export function EngineeringGeometryResearchPage({ lang = 'en' }: { lang?: Lang }) {
  const ja = lang === 'ja'
  const research = ja ? '/ja/research' : '/research'
  const counterpart = ja ? '/research/engineering-geometry' : '/ja/research/engineering-geometry'

  return (
    <main className={styles.page} id="top">
      <ShaderField className={styles.backgroundField} />
      <div className={styles.backgroundVeil} aria-hidden="true" />
      <LabNotchNav lang={lang} active="research" alternateHref={counterpart} />

      <section className={styles.hero}>
        <div className={styles.shell}>
          <Link className={styles.backLink} href={research}>
            <ArrowLeft size={14} aria-hidden="true" />
            {ja ? '研究一覧' : 'Research index'}
          </Link>

          <div className={styles.heroCopy}>
            <p className={styles.sectionLabel}>ENGINEERING GEOMETRY / 2026.08.31</p>
            <h1>{ja ? '同じ8つの射から、立体と図面を生成する。' : 'One set of eight morphisms produces both solids and drawings.'}</h1>
            <p>{ja
              ? '部品名ごとの命令を増やさず、型付き構成から厳密な3D形状、第三角法、隠れ線、断面、寸法、交換ファイルまでを一度に導出しました。'
              : 'Without adding part-specific commands, a typed construction now derives exact 3D solids, third-angle views, hidden lines, sections, dimensions and exchange files.'}</p>
          </div>

          <div className={styles.metricRail} aria-label={ja ? '実験結果' : 'Experiment results'}>
            <div><strong>8</strong><span>{ja ? '共通射' : 'generic morphisms'}</span></div>
            <div><strong>11 / 11</strong><span>{ja ? '妥当なB-rep' : 'valid B-reps'}</span></div>
            <div><strong>0</strong><span>{ja ? '未見用の新演算' : 'new holdout operations'}</span></div>
            <div><strong>44</strong><span>{ja ? '図面・交換成果物' : 'drawing and exchange artifacts'}</span></div>
          </div>

          <figure className={styles.heroDrawing}>
            <Image
              src="/research/engineering-geometry/spoked-wheel.svg"
              alt={ja ? 'MORTRAが生成したスポーク車輪の第三角法機械図面' : 'Third-angle mechanical drawing of a spoked wheel generated by MORTRA'}
              fill
              priority
              unoptimized
              sizes="(max-width: 900px) 100vw, 1240px"
            />
            <figcaption>
              <span>SPK-001</span>
              {ja ? '形状族未見 / 第三角法・断面A-A・主要寸法' : 'Topology holdout / third-angle projection, section A-A and principal dimensions'}
            </figcaption>
          </figure>
        </div>
      </section>

      <section className={styles.section} id="basis">
        <div className={styles.shell}>
          <div className={styles.sectionHead}>
            <div>
              <p className={styles.sectionLabel}>01 / GENERATIVE BASIS</p>
              <h2>{ja ? '部品ではなく、操作を記述する。' : 'Describe operations, not parts.'}</h2>
            </div>
            <p>{ja
              ? '押出し、回転、ロフトは別の原始命令ではありません。いずれも断面を経路に沿って運ぶ sweep の条件違いです。部品名を覚えず、構成の合成だけを保存します。'
              : 'Extrusion, revolution and lofting are not separate primitives. They are parameterizations of sweep: transporting a section along a path. MORTRA stores compositions, not part names.'}</p>
          </div>

          <div className={styles.operationGrid}>
            {operations.map(([name, description], index) => (
              <div key={name}>
                <span>{String(index + 1).padStart(2, '0')}</span>
                <code>{name}</code>
                <p>{ja ? description : [
                  'Change position, orientation or symmetry',
                  'Transport a section along a trajectory',
                  'Take union, difference or intersection',
                  'Select faces, edges or boundaries',
                  'Intersect a shape with a cutting flat',
                  'Map a solid to orthographic or isometric views',
                  'Check dimensions and validity conditions',
                  'Attach dimensions, centrelines and notes',
                ][index]}</p>
              </div>
            ))}
          </div>

          <div className={styles.typeRule}>
            <div>
              <span>{ja ? '同じ型規則' : 'ONE TYPE RULE'}</span>
              <strong>sweep<sub>d</sub> : Cell(k, R<sup>n</sup>) → Cell(min(k+d,n), R<sup>n</sup>)</strong>
            </div>
            <p>{ja
              ? '平面断面を3次元へ押し出す場合も、3次元セルを4次元で運ぶ場合も語彙は同じです。現在の厳密CAD実行はOpenCascadeの対応範囲である3次元までです。'
              : 'The vocabulary is unchanged when a plane section becomes a 3D solid or a 3D cell is swept in 4D. The exact OpenCascade execution backend currently stops at three dimensions.'}</p>
          </div>
        </div>
      </section>

      <section className={`${styles.section} ${styles.pipelineSection}`} id="pipeline">
        <div className={styles.shell}>
          <div className={styles.sectionHead}>
            <div>
              <p className={styles.sectionLabel}>02 / ONE CONSTRUCTION DAG</p>
              <h2>{ja ? '立体と図面を、別々に描かない。' : 'The solid and drawing are never authored separately.'}</h2>
            </div>
            <p>{ja
              ? '表示用の輪郭を手書きせず、投影線、隠れ線、断面、ハッチをすべて同じB-repから導出します。形状を直せば図面も同時に変わります。'
              : 'No display outline is hand-authored. Projection lines, hidden lines, sections and hatching are all derived from the same B-rep, so a geometry change propagates to the drawing.'}</p>
          </div>

          <div className={styles.pipeline}>
            {pipeline.map(([index, title, detail], itemIndex) => (
              <div key={title}>
                <span>{index}</span>
                <strong>{title}</strong>
                <p>{ja ? detail : [
                  'Record the construction with Cell(k, R^n) and eight morphisms',
                  'Execute solid geometry and topology in OpenCascade',
                  'Derive projection, hidden lines and sections from the B-rep',
                  'Attach centrelines, dimensions and notes to semantic entities',
                  'Persist STEP, STL, SVG, DXF and replay JSON',
                ][itemIndex]}</p>
                {itemIndex < pipeline.length - 1 ? <ArrowRight size={15} aria-hidden="true" /> : null}
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.section} id="drawings">
        <div className={styles.shell}>
          <div className={styles.sectionHead}>
            <div>
              <p className={styles.sectionLabel}>03 / TOPOLOGY HOLDOUTS</p>
              <h2>{ja ? '基底に無かった形状族で試す。' : 'Test shapes absent from the basis set.'}</h2>
            </div>
            <p>{ja
              ? '寸法を変えただけの評価ではありません。基底5族に含まれない反復スポーク、二枚ラグ、三軸交差流路を固定し、演算集合を変えずに生成しました。'
              : 'These are not dimension-only variants. Repeated spokes, paired lugs and three-axis intersecting passages were held out from the five-family basis and generated without changing the operator set.'}</p>
          </div>

          <div className={styles.drawingList}>
            {drawings.map(drawing => (
              <figure key={drawing.id}>
                <div className={styles.drawingCanvas}>
                  <Image src={drawing.src} alt={ja ? `${drawing.ja}の機械図面` : `Mechanical drawing of ${drawing.en}`} fill loading="eager" unoptimized sizes="(max-width: 900px) 100vw, 1200px" />
                </div>
                <figcaption>
                  <span>{drawing.id}</span>
                  <strong>{ja ? drawing.ja : drawing.en}</strong>
                  <p>{ja ? drawing.detailJa : drawing.detailEn}</p>
                </figcaption>
              </figure>
            ))}
          </div>
        </div>
      </section>

      <section className={`${styles.section} ${styles.resultsSection}`} id="results">
        <div className={styles.shell}>
          <div className={styles.sectionHead}>
            <div>
              <p className={styles.sectionLabel}>04 / MEASURED RESULT</p>
              <h2>{ja ? '画像ではなく、形状と成果物を検査する。' : 'Verify geometry and artifacts, not screenshots alone.'}</h2>
            </div>
            <p>{ja
              ? '各ケースでB-repの妥当性、単一ソリッド、正体積、閉形式体積、断面、投影領域、出力ファイルを独立に検査しました。'
              : 'Each case independently checks B-rep validity, single-solid topology, positive and closed-form volume, sections, view bounds and exported files.'}</p>
          </div>

          <div className={styles.resultTable}>
            {resultRows.map(([label, value, note]) => (
              <div key={label}>
                <span>{ja ? label : {
                  '基底形状族': 'Basis families',
                  '寸法未見': 'Parameter holdouts',
                  '形状族未見': 'Topology holdouts',
                  '厳密形状': 'Exact solids',
                  '投影図': 'Projected views',
                  '追加した演算族': 'Added operator families',
                }[label]}</span>
                <strong>{value}</strong>
                <p>{ja ? note : {
                  'フランジ、段付き軸、ブラケット、遷移ダクト、格子': 'Flange, stepped shaft, bracket, transition duct and lattice',
                  '寸法・穴数を変えた未見パラメータ': 'Unseen dimensions and hole counts',
                  'スポーク車輪、クレビス、三軸交差流路': 'Spoked wheel, clevis and cross-drilled manifold',
                  '妥当な単一ソリッドとして再生': 'Replayed as valid single solids',
                  'TOP、FRONT、RIGHT、ISOMETRICが図面内に収容': 'TOP, FRONT, RIGHT and ISOMETRIC fit their view regions',
                  '未見6件のための部品別命令は追加していない': 'No part-specific command was added for the six holdouts',
                }[note]}</p>
              </div>
            ))}
          </div>

          <div className={styles.artifactLinks}>
            <a href="/research/engineering-geometry/spoked-wheel.step" download>
              <Box size={18} aria-hidden="true" /><span><b>STEP</b><small>{ja ? '厳密3D形状' : 'exact 3D solid'}</small></span><Download size={14} aria-hidden="true" />
            </a>
            <a href="/research/engineering-geometry/spoked-wheel.dxf" download>
              <Ruler size={18} aria-hidden="true" /><span><b>DXF</b><small>{ja ? '機械図面' : 'technical drawing'}</small></span><Download size={14} aria-hidden="true" />
            </a>
            <a href="/research/engineering-geometry/summary.json" target="_blank" rel="noreferrer">
              <FileJson2 size={18} aria-hidden="true" /><span><b>JSON</b><small>{ja ? '11件の実測結果' : 'results for all 11 cases'}</small></span><ArrowRight size={14} aria-hidden="true" />
            </a>
            <a href="https://github.com/corcondor/mortra/blob/release/mortra-1-beta/docs/research/MORTRA-DIMENSION-INDEPENDENT-ENGINEERING-GEOMETRY-20260831.md" target="_blank" rel="noreferrer">
              <Github size={18} aria-hidden="true" /><span><b>{ja ? '研究記録' : 'Research record'}</b><small>{ja ? '原理・方法・結果・限界' : 'principle, method, result and limits'}</small></span><ArrowRight size={14} aria-hidden="true" />
            </a>
          </div>
        </div>
      </section>

      <section className={styles.section} id="boundary">
        <div className={`${styles.shell} ${styles.boundaryGrid}`}>
          <div>
            <p className={styles.sectionLabel}>05 / CURRENT BOUNDARY</p>
            <h2>{ja ? '次に増やすのは、部品名ではない。' : 'The next additions are not part names.'}</h2>
          </div>
          <div className={styles.boundaryCopy}>
            <p>{ja
              ? '今回示したのは幾何と図面です。材料、荷重、疲労、熱、加工公差、表面粗さ、GD&T、組立順序、BOMはまだ実行対象ではありません。これらを constrain と annotate へ型付きで接続することが次の工学的課題です。'
              : 'This experiment covers geometry and drawing. Material, loads, fatigue, heat, manufacturing tolerance, surface finish, GD&T, assembly sequence and BOM are not executable yet. The next engineering task is to connect them to constrain and annotate with explicit types.'}</p>
            <p>{ja
              ? '図面は第三角法、隠れ線、中心線、断面、主要寸法を備えますが、ASMEまたはISOへの適合認証は行っていません。4次元は型検査までで、厳密形状backendは3次元です。'
              : 'The drawings include third-angle projection, hidden lines, centrelines, sections and principal dimensions, but have not been certified against ASME or ISO. Four-dimensional use is type-checked only; the exact geometry backend is three-dimensional.'}</p>
          </div>
        </div>
      </section>

      <footer className={styles.footer}>
        <div className={styles.shell}>
          <span><Layers3 size={14} aria-hidden="true" />MORTRA / ENGINEERING GEOMETRY</span>
          <Link href={research}>{ja ? '研究一覧へ戻る' : 'Back to research'}<ArrowRight size={13} /></Link>
        </div>
      </footer>
    </main>
  )
}
